"""initial schema

Revision ID: 25748187f583
Revises: 
Create Date: 2025-01-31 20:00:43.779237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25748187f583'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_movie_ratings')
    op.add_column('movies', sa.Column('popularity_score', sa.Float(), nullable=False))
    op.add_column('movies', sa.Column('rating_count', sa.Integer(), nullable=False))
    op.add_column('movies', sa.Column('view_count', sa.Integer(), nullable=False))
    op.add_column('movies', sa.Column('completion_rate', sa.Float(), nullable=False))
    op.add_column('movies', sa.Column('keywords', sa.String(length=1000), nullable=True))
    op.add_column('movies', sa.Column('similar_movies', sa.String(length=500), nullable=True))
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ratings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('users', sa.Column('favorite_genres', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('preferred_languages', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('content_preferences', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'content_preferences')
    op.drop_column('users', 'preferred_languages')
    op.drop_column('users', 'favorite_genres')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'ratings', 'users', ['user_id'], ['id'])
    op.drop_column('movies', 'similar_movies')
    op.drop_column('movies', 'keywords')
    op.drop_column('movies', 'completion_rate')
    op.drop_column('movies', 'view_count')
    op.drop_column('movies', 'rating_count')
    op.drop_column('movies', 'popularity_score')
    op.create_table('user_movie_ratings',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('movie_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.CheckConstraint('rating >= 0 AND rating <= 5'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    # ### end Alembic commands ###
